export enum MenteePreferencesFieldNames {
  MEET_FREQUENCY = 'MEET_FREQUENCY',
  MEET_DURATION = 'MEET_DURATION',
}

export enum MentorPreferencesFieldNames {
  RECOMMEND_NUMBER_OF_MEETINGS_INITIAL = 'RECOMMEND_NUMBER_OF_MEETINGS_INITIAL',
  RECOMMEND_NUMBER_OF_MEETINGS_SUBSEQUENT = 'RECOMMEND_NUMBER_OF_MEETINGS_SUBSEQUENT',
}
